spring.application.name=boutique

# Server Port (Render provides this automatically)
server.port=${PORT:8080}

# Database Connection (Defaults to Neon for local testing)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-hidden-lab-anxn3tar-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_pUYV25nKhiAg}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Custom Security Key
boutique.api.key=${BOUTIQUE_API_KEY:dev-key}